Repository LY-HackU-2025-team8/taaks, pull requests merged in 2025-05, with the labels that each got.

#113 ナビゲーションの改善
  frontend_react/src/app/api/check-login.ts
  frontend_react/src/app/routes/_app.tsx
  frontend_react/src/app/routes/_auth.tsx
  frontend_react/src/app/routes/_auth/login.tsx
  frontend_react/src/app/routes/index.tsx
  frontend_react/src/index.css
Labels: セルフマージ

#119 issue templateの更新
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/task.yml
Labels: セルフマージ

#121 GitHub Actionsワークフローを追加し、PR作成時にリンクされたIssueのフィールドをPRカードにコピーする機能を実装
  .github/workflows/copy_issue_fields_when_pr_created.yml
Labels: セルフマージ

#129 修正：リンクされたIssueが見つからない場合の処理を追加し、以降のステップをスキップするように修正
  .github/workflows/copy_issue_fields_when_pr_created.yml
Labels: セルフマージ

#144 Add Springdoc OpenAPI configuration and update security settings for …
  backend/build.gradle
  backend/src/main/java/com/team8/taak/config/SecurityConfig.java
  backend/src/main/resources/application.properties
Labels: セルフマージ

#140 簡易的ログアウトボタンを実装
  frontend_react/src/app/routes/_app.tsx
  frontend_react/src/app/routes/_app/account.tsx
  frontend_react/src/route-tree.gen.ts
Labels: セルフマージ

#150 springbootをホスト上で実行する形に修正
  backend/compose.yaml
Labels: セルフマージ

#154 タスクテンプレートに依存関係フィールドを追加
  .github/ISSUE_TEMPLATE/task.yml
Labels: セルフマージ

#155 ツールへのリンクを追加
  frontend_react/src/app/routes/_app/buddy.tsx
  frontend_react/src/app/routes/_app/dashboard.tsx
  frontend_react/src/app/routes/_app/todo.tsx
  frontend_react/src/pages/dashboard/ui/dashboard.tsx
  frontend_react/src/pages/dashboard/ui/tool-link.tsx
  frontend_react/src/route-tree.gen.ts
  frontend_react/src/shared/ui/page/page-header.tsx
  frontend_react/src/shared/ui/page/page-title-container.tsx
  frontend_react/src/shared/ui/page/page-title.tsx
Labels: セルフマージ

#90 [Task]: TODOカードをコンポーネントとして実装
  frontend_react/package.json
  frontend_react/src/fonts.css
  frontend_react/src/index.css
  frontend_react/src/shared/ui/components/custom/small-card.tsx
  package-lock.json
Labels: タスク

#168 Feature/134 users/me
  backend/src/main/java/com/team8/taak/config/AuthorizeFilter.java
  backend/src/main/java/com/team8/taak/config/JwtTokenUtil.java
  backend/src/main/java/com/team8/taak/config/LoginFilter.java
  backend/src/main/java/com/team8/taak/config/SecurityConfig.java
  backend/src/main/java/com/team8/taak/controller/GlobalAuthExceptionHandler.java
  backend/src/main/java/com/team8/taak/controller/LoginController.java
  frontend_react/src/shared/api/api-spec.ts
  openapi/openapi.yaml
Labels: ユーザー

#170 Add spring-boot-devtools as a development-only dependency
  backend/build.gradle
Labels: セルフマージ

#122 タスクに関するデータモデルとAPIの作成
  backend/src/main/java/com/team8/taak/controller/TaskController.java
  backend/src/main/java/com/team8/taak/model/TaakTask.java
  backend/src/main/java/com/team8/taak/model/TaakTaskRepository.java
Labels: タスク

#180 fix: adjust the type of return value to JSON
  backend/src/main/java/com/team8/taaks/controller/TaskController.java
  frontend_react/src/shared/api/api-spec.ts
  openapi/openapi.yaml
Labels: タスク

#191 fix: fixed path on build file
  backend/Procfile
Labels: セルフマージ

#193 fix: specify the port
  backend/Procfile
Labels: セルフマージ

#177 タスク登録ドロワの実装
  .github/workflows/test_pull_requests.yml
  frontend_react/package.json
  frontend_react/src/app/routes/_auth/login.tsx
  frontend_react/src/features/add-task/ui/add-task-drawer.tsx
  frontend_react/src/shared/api/openapi-fetch.ts
  frontend_react/src/shared/ui/components/input/date-picker.tsx
  frontend_react/src/shared/ui/components/input/inline-textarea.tsx
  frontend_react/src/shared/ui/components/shadcn/calendar.tsx
  frontend_react/src/shared/ui/components/shadcn/drawer.tsx
  frontend_react/src/shared/ui/components/shadcn/slider.tsx
  frontend_react/vite.config.ts
  package-lock.json
Labels: セルフマージ, タスク

#207 fix: set app name of heroku as `vars`
  .github/workflows/deploy.yml
Labels: セルフマージ

#208 feat: add Buddy entity and repository for user buddies management
  backend/schema.sql
  backend/src/main/java/com/team8/taaks/model/Buddy.java
  backend/src/main/java/com/team8/taaks/model/BuddyRepository.java
Labels: セルフマージ

#215 タスクの通知に関するデータベーステーブルの設計・実装
  backend/schema.sql
  backend/src/main/java/com/team8/taaks/config/SecurityConfig.java
  backend/src/main/java/com/team8/taaks/controller/BuddyController.java
  backend/src/main/java/com/team8/taaks/controller/DiariesApi.java
  backend/src/main/java/com/team8/taaks/controller/DiariesController.java
  backend/src/main/java/com/team8/taaks/controller/TaskController.java
  backend/src/main/java/com/team8/taaks/dto/DiaryRequest.java
  backend/src/main/java/com/team8/taaks/dto/DiaryResponse.java
  backend/src/main/java/com/team8/taaks/dto/DiarySummary.java
  backend/src/main/java/com/team8/taaks/model/NotificationTargetToken.java
  backend/src/main/java/com/team8/taaks/model/TaakUserDetailManager.java
  backend/src/main/java/com/team8/taaks/model/TaskReminder.java
  backend/src/main/java/com/team8/taaks/repository/BuddyRepository.java
  backend/src/main/java/com/team8/taaks/repository/DiaryRepository.java
  backend/src/main/java/com/team8/taaks/repository/NotificationTargetTokenRepository.java
  backend/src/main/java/com/team8/taaks/repository/TaakTaskRepository.java
  backend/src/main/java/com/team8/taaks/repository/TaakUserRepository.java
  backend/src/main/java/com/team8/taaks/repository/TaskReminderRepository.java
Labels: セルフマージ

#217 日記を記録するフロント画面の実装
  frontend_react/.env.example
  frontend_react/src/app/routes/__root.tsx
  frontend_react/src/app/routes/_app.tsx
  frontend_react/src/app/routes/_app/_tab-top-pages.tsx
  frontend_react/src/app/routes/_app/_tab-top-pages/account.tsx
  frontend_react/src/app/routes/_app/_tab-top-pages/buddy.tsx
  frontend_react/src/app/routes/_app/_tab-top-pages/dashboard.tsx
  frontend_react/src/app/routes/_app/_tab-top-pages/diary.tsx
  frontend_react/src/app/routes/_app/_tab-top-pages/todo.tsx
  frontend_react/src/app/routes/_app/diary.tsx
  frontend_react/src/app/routes/_app/diary/new.tsx
  frontend_react/src/index.css
  frontend_react/src/pages/diary/ui/new-diary-form.tsx
  frontend_react/src/route-tree.gen.ts
  frontend_react/src/shared/ui/components/icons/chevron-right-icon.tsx
  frontend_react/src/shared/ui/components/icons/close-icon.tsx
  frontend_react/src/shared/ui/components/icons/edit-icon.tsx
  frontend_react/src/shared/ui/components/icons/home-icon.tsx
  frontend_react/src/shared/ui/components/icons/memo-pad-icon.tsx
  frontend_react/src/shared/ui/components/icons/note-icon.tsx
  frontend_react/src/shared/ui/components/icons/notification-icon.tsx
  frontend_react/src/shared/ui/components/icons/plus-icon.tsx
  frontend_react/src/shared/ui/components/icons/tag-icon.tsx
  frontend_react/src/shared/ui/components/icons/todo-icon.tsx
  frontend_react/src/shared/ui/components/icons/user-icon.tsx
  frontend_react/src/shared/ui/components/shadcn/button.tsx
  frontend_react/src/shared/ui/page/page-main.tsx
  frontend_react/src/vite-env.d.ts
Labels: 日記

#231 タスクを登録する際に通知時刻を設定しないとエラーが出るバグの対応 #229
  backend/src/main/java/com/team8/taaks/controller/TaskController.java
Labels: セルフマージ, タスク

#228 タスクの絞り込みのAPI実装
  backend/src/main/java/com/team8/taaks/controller/ApiUtil.java
  backend/src/main/java/com/team8/taaks/controller/DiariesApi.java
  backend/src/main/java/com/team8/taaks/controller/DiariesController.java
  backend/src/main/java/com/team8/taaks/controller/TaskController.java
  backend/src/main/java/com/team8/taaks/dto/TaskRequest.java
  backend/src/main/java/com/team8/taaks/dto/TaskResponse.java
  backend/src/main/java/com/team8/taaks/repository/TaakTaskRepository.java
  backend/src/main/java/com/team8/taaks/specification/TaakTaskSpecification.java
  frontend_react/src/shared/api/api-spec.ts
  openapi/openapi.yaml
Labels: タスク

#247 タスクを完了/未完了にできる
  frontend_react/src/entities/task/api/use-create-task.ts
  frontend_react/src/entities/task/api/use-edit-task.ts
  frontend_react/src/entities/task/ui/task-card-large.tsx
Labels: タスク

#251 APIの戻り値の型がundefinedを含まないようにする
  backend/src/main/java/com/team8/taaks/dto/ErrorResponse.java
  backend/src/main/java/com/team8/taaks/dto/GenericMessageResponse.java
  backend/src/main/java/com/team8/taaks/dto/LoginResponse.java
  backend/src/main/java/com/team8/taaks/dto/NotificationTargetTokenResponse.java
  backend/src/main/java/com/team8/taaks/dto/TaskResponse.java
  backend/src/main/java/com/team8/taaks/dto/UsersResponse.java
  frontend_react/src/shared/api/api-spec.ts
  openapi/openapi.yaml
Labels: セルフマージ

#277 rive-check-button の更新
  frontend_react/public/assets/animations/taaks_checkbtn.riv
  frontend_react/src/shared/ui/components/custom/rive-check-button.tsx
Labels: セルフマージ

#284 おすすめタスクAPI
  backend/src/main/java/com/team8/taaks/controller/SuggestedTaskController.java
  backend/src/main/java/com/team8/taaks/service/OpenAiChatService.java
  backend/src/main/java/com/team8/taaks/service/SuggestedTaskService.java
  backend/src/main/java/com/team8/taaks/service/SuggestedTaskServiceImple.java
  frontend_react/src/shared/api/api-spec.ts
  openapi/openapi.yaml
Labels: セルフマージ

#297 Spring Boot を3.4.5から3.4.6へアップデート
  backend/build.gradle
Labels: セルフマージ

#298 Feature/283 login buddy decoration
  frontend_react/public/assets/images/diary_3d.png
  frontend_react/public/assets/videos/buddies.mp4
  frontend_react/src/app/routes/_app/create-buddy/index.tsx
  frontend_react/src/app/routes/_app/create-buddy/nickname.tsx
  frontend_react/src/app/routes/_auth.tsx
  frontend_react/src/app/routes/_auth/login.tsx
  frontend_react/src/app/routes/index.tsx
  frontend_react/src/pages/create-buddy/api/use-create-buddy-step.ts
  frontend_react/src/pages/dashboard/ui/dashboard-buddy.tsx
  frontend_react/src/route-tree.gen.ts
  frontend_react/src/shared/ui/components/icons/taaks-logo.tsx
Labels: セルフマージ

#312 Feature/281 diary task suggetion endpoint
  backend/src/main/java/com/team8/taaks/config/NotificationBatchConfig.java
  backend/src/main/java/com/team8/taaks/controller/DiariesController.java
  backend/src/main/java/com/team8/taaks/dto/GeneratedTask.java
  backend/src/main/java/com/team8/taaks/dto/GeneratedTaskResponse.java
  backend/src/main/java/com/team8/taaks/dto/GeneratedTasks.java
  backend/src/main/java/com/team8/taaks/service/ChatService.java
  backend/src/main/java/com/team8/taaks/service/OpenAiChatService.java
  frontend_react/src/shared/api/api-spec.ts
  openapi/openapi.yaml
Labels: セルフマージ

#314 タスク登録の際に、AIで計算するかマニュアルで指定するかを選ぶ（バックエンド）
  backend/src/main/java/com/team8/taaks/controller/TaskController.java
  backend/src/main/java/com/team8/taaks/dto/TaskRegisterRequest.java
  frontend_react/src/shared/api/api-spec.ts
  openapi/openapi.yaml
Labels: セルフマージ
